name: Publish NPM Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: 'gmsllc'
      # debug in case publish fails
      - run: cat .npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
